spring:
  mvc:
    pathmatch:
      # For Swagger 3.0
      matching-strategy: ant_path_matcher
  # Mysql Connection Settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bomsbro.com:3307/bomsbro_blog?serverTimezone=Asia/Seoul
    username: bomsbro_api
    password: qwer1234!
  # JPA Settings
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
      ddl-auto: create-drop
  sql:
    init:
      mode: always
#TODO: Change Secret Key
jwt:
  header: Authorization
  secret: "Ym9tc2Jyby1ibG9nLXByb2plY3QtamF2YS13ZWJ0b2tlbi1zZWNyZXQtY29kZS1nZW5lcmF0ZQo="
  token-validity-in-seconds: 86400
logging:
  level:
    org.hibernate.SQL: debug