spring:
  mvc:
    # For Swagger 3.0
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_local_db
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
#TODO: Change Secret Key
jwt:
  header: Authorization
  secret: "Ym9tc2Jyby1ibG9nLXByb2plY3QK"
  token-validity-in-seconds: 86400
logging:
  level:
    org.hibernate.SQL: debug