INSERT INTO USER (USER_ID, USER_PASSWORD, USER_NAME,  NICKNAME, ACTIVATED);
VALUES (1, 'admin', 'qwer1234!', 'bomsbro', true);

INSERT INTO AUTHORITY (AUTH_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTH_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (user_id, auth_name) values (1, 1);
INSERT INTO USER_AUTHORITY (user_id, auth_name) values (1, 2);